### ISSUE TITLE
Debug info

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [SimoneS93/xtremecache#2]
First of all thank you for this aresome extension! My product pages load under 150 ms for non logged in users! It cuts off load time inway ahead  abount 10-15 times! I am using sqlite engine for caching on my distributed file system in a clustered environment.

One issue I noticed that turning on Debug mode does no effect on http headers. Would you please troubleshoot the extension?

I cloned it from https://github.com/kik-off/xtremecache fork since it is way ahead of your branch. Usin PS 1.6.1.2

**Comment by SimoneS93** [comment]
If you want to disable cache when _PS_MODE_DEV_ is on, I edited the isActive method on the 1.0.6 version. You can try it out.

**Comment by devdesco-ceo** [comment]
No, I am asking about enabling "Debug" option "Add debug information in the response, e.g. "served from cache with key 5d5d5cdc66c75d6e40fdb5357d6436b0 [driver: files]". Where does it have output? I do not see it in cookies though...

**Comment by SimoneS93** [comment]
You can transform the output as you like in hookActionRequestComplete. I've edited xtremecache.1.0.6 with cache key, driver and timestamp debug info.

**Comment by SimoneS93** [comment]
Is it solved?
