### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by tomershvueli** [SimoneS93/xtremecache#3]
How would one go about installing this as a Prestashop module? I tried uploading the xtremecache.zip after I downloaded the repo, but it's not showing up under the list of modules, ideas?

**Comment by vortexfoto** [comment]
same here

**Comment by SimoneS93** [comment]
This is an old module. Stop using it.

**Comment by PERCE-NEIGE** [comment]
Please, update your description to make people know it's not compatible anymore.

**Comment by SimoneS93** [comment]
Done
